version: "2.4"
services:
  server:
    environment:
      - LBA_ENV=recette
      - LBA_LOG_LEVEL=info
      - LBA_LOG_DESTINATIONS=stdout,mongodb
      - LBA_PUBLIC_URL=https://doctrina-recette.apprentissage.beta.gouv.fr
      - LBA_API_KEY={{ vault[env_type].LBA_API_KEY }}

  ui:
    environment:
      - LBA_ENV=recette
      - LBA_PUBLIC_URL=https://doctrina-recette.apprentissage.beta.gouv.fr
    volumes:
      - /opt/doctrina/.overrides/ui/robots.txt:/app/public/robots.txt:ro

  ui_espace_pro:
    build:
      args:
        - REACT_APP_BASE_URL=https://doctrina-recette.apprentissage.beta.gouv.fr/api
        - REACT_APP_METABASE_URL=https://doctrina-recette.apprentissage.beta.gouv.fr/metabase
        - REACT_APP_ENV=recette
