version: "2.4"
services:
  reverse_proxy:
    ports:
      - 443:443
    volumes:
      - /opt/doctrina/data/nginx:/data
      - /opt/doctrina/data/ssl:/ssl:ro
    environment:
      - SERVER_NAME={{dns_name}}
      - NGINX_ALWAYS_TLS_REDIRECT=true
      - PROXY_SSL_CERT=/ssl/fullchain.pem
      - PROXY_SSL_CERT_KEY=/ssl/privkey.pem


  server:
    volumes:
      - /opt/doctrina/data/server:/data

  mongodb:
    volumes:
      - /opt/doctrina/data/mongodb/db:/data/db
      - /opt/doctrina/data/mongodb/configdb:/data/configdb
      - /opt/doctrina/data/mongodb/backups:/data/backups
      - /opt/doctrina/.overrides/mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  elasticsearch:
    volumes:
      - /opt/doctrina/data/elasticsearch:/usr/share/elasticsearch/data
