version: "2.4"
services:
  reverse_proxy:
    ports:
      - 443:443
    volumes:
      - /opt/doctrina/data/nginx:/data
      - /opt/doctrina/data/ssl:/ssl:ro
    environment:
      - SERVER_NAME={{dns_name}}
      - NGINX_ALWAYS_TLS_REDIRECT=true
      - PROXY_SSL_CERT=/ssl/fullchain.pem
      - PROXY_SSL_CERT_KEY=/ssl/privkey.pem


  server:
    environment:
      - AWS_ACCESS_KEY_ID={{ vault.AWS_ACCESS_KEY_ID }}
      - AWS_SECRET_ACCESS_KEY={{ vault.AWS_SECRET_ACCESS_KEY }}
      - LABONNEALTERNANCE_MONGODB_URI=mongodb://mongodb:27017/labonnealternance?retryWrites=true&w=majority      
      - LABONNEALTERNANCE_SECRET_UPDATE_ROMES_METIERS={{ vault.LABONNEALTERNANCE_SECRET_UPDATE_ROMES_METIERS }}
      - LABONNEFORMATION_PASSWORD={{ vault.LABONNEFORMATION_PASSWORD }}
      - LABONNEALTERNANCE_SMTP_AUTH_USER={{ vault.LABONNEALTERNANCE_SMTP_AUTH_USER }}
      - LABONNEALTERNANCE_SMTP_AUTH_PASS={{ vault.LABONNEALTERNANCE_SMTP_AUTH_PASS }}
      - LABONNEALTERNANCE_SMTP_SENDINBLUE_TOKEN={{ vault.LABONNEALTERNANCE_SMTP_SENDINBLUE_TOKEN }}
      - LABONNEALTERNANCE_SENDINBLUE_API_KEY={{ vault.LABONNEALTERNANCE_SENDINBLUE_API_KEY }}
      - LABONNEALTERNANCE_SLACK_WEBHOOK_URL={{ vault.LABONNEALTERNANCE_SLACK_WEBHOOK_URL }}
      - LABONNEALTERNANCE_JOB_SLACK_WEBHOOK={{ vault.LABONNEALTERNANCE_JOB_SLACK_WEBHOOK }}
      - LABONNEALTERNANCE_ALLOWED_SOURCES={{ vault.LABONNEALTERNANCE_ALLOWED_SOURCES }}
      - MATCHA_ACCESS_KEY={{ vault.MATCHA_ACCESS_KEY }}
      - API_ENTREPRISE_KEY={{ vault.API_ENTREPRISE_KEY }}
      - ESD_CLIENT_ID={{ vault.ESD_CLIENT_ID }}
      - ESD_CLIENT_SECRET={{ vault.ESD_CLIENT_SECRET }}
      - SENTRY_AUTH_TOKEN={{ vault.SENTRY_AUTH_TOKEN }}
      - SERVER_SENTRY_DSN={{ vault.SERVER_SENTRY_DSN }}
      - LABONNEALTERNANCE_API_KEY={{ vault['env_type'].LABONNEALTERNANCE_API_KEY }}
      #- LABONNEALTERNANCE_AUTH_USER_JWT_SECRET={{ vault.LABONNEALTERNANCE_AUTH_USER_JWT_SECRET }}
      #- LABONNEALTERNANCE_AUTH_ACTIVATION_JWT_SECRET={{ vault.LABONNEALTERNANCE_AUTH_ACTIVATION_JWT_SECRET }}
      #- LABONNEALTERNANCE_AUTH_PASSWORD_JWT_SECRET={{ vault.LABONNEALTERNANCE_AUTH_PASSWORD_JWT_SECRET }}

    volumes:
      - /opt/doctrina/data/server:/data

  ui:
    environment:
      - SENTRY_ORG=mna-idea
      - SENTRY_PROJECT=labonnealternance-ui
      - SENTRY_AUTH_TOKEN={{ vault.SENTRY_AUTH_TOKEN }}
      - SERVER_SENTRY_DSN={{ vault.SERVER_SENTRY_DSN }}
      - UI_SENTRY_DSN={{ vault.UI_SENTRY_DSN }}

  mongodb:
    volumes:
      - /opt/doctrina/data/mongodb/db:/data/db
      - /opt/doctrina/data/mongodb/configdb:/data/configdb
      - /opt/doctrina/data/mongodb/backups:/data/backups
      - /opt/doctrina/.overrides/mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  elasticsearch:
    volumes:
      - /opt/doctrina/data/elasticsearch:/usr/share/elasticsearch/data
