version: "2.4"
services:
  reverse_proxy:
    ports:
      - 443:443
    volumes:
      - /opt/doctrina/data/nginx:/data
      - /opt/doctrina/data/ssl:/ssl:ro
    environment:
      - SERVER_NAME={{dns_name}}
      - NGINX_ALWAYS_TLS_REDIRECT=true
      - PROXY_SSL_CERT=/ssl/fullchain.pem
      - PROXY_SSL_CERT_KEY=/ssl/privkey.pem

  server:
    environment:
      - LBA_AWS_ACCESS_KEY_ID={{ vault.LBA_AWS_ACCESS_KEY_ID }}
      - LBA_AWS_SECRET_ACCESS_KEY={{ vault.LBA_AWS_SECRET_ACCESS_KEY }}
      - LBA_MONGODB_URI=mongodb://labonnealternance:{{ vault.LBA_MONGODB_USER_PASSWORD }}@mongodb:27017/labonnealternance?authSource=admin&retryWrites=true&w=majority
      - LBA_SECRET_UPDATE_ROMES_METIERS={{ vault.LBA_SECRET_UPDATE_ROMES_METIERS }}
      - LBA_LABONNEFORMATION_PASSWORD={{ vault.LBA_LABONNEFORMATION_PASSWORD }}
      - LBA_SLACK_WEBHOOK_URL={{ vault.LBA_SLACK_WEBHOOK_URL }}
      - LBA_JOB_SLACK_WEBHOOK={{ vault.LBA_JOB_SLACK_WEBHOOK }}
      - LBA_ALLOWED_SOURCES={{ vault.LBA_ALLOWED_SOURCES }}
      - LBA_MATCHA_ACCESS_KEY={{ vault.LBA_MATCHA_ACCESS_KEY }}
      - LBA_API_ENTREPRISE_KEY={{ vault.LBA_API_ENTREPRISE_KEY }}
      - LBA_ESD_CLIENT_ID={{ vault.LBA_ESD_CLIENT_ID }}
      - LBA_ESD_CLIENT_SECRET={{ vault.LBA_ESD_CLIENT_SECRET }}
      - LBA_SENTRY_AUTH_TOKEN={{ vault.LBA_SENTRY_AUTH_TOKEN }}
      - LBA_SERVER_SENTRY_DSN={{ vault.LBA_SERVER_SENTRY_DSN }}
      - LBA_AUTH_USER_JWT_SECRET={{ vault.LBA_AUTH_USER_JWT_SECRET }}
      - LBA_AUTH_ACTIVATION_JWT_SECRET={{ vault.LBA_AUTH_ACTIVATION_JWT_SECRET }}
      - LBA_AUTH_PASSWORD_JWT_SECRET={{ vault.LBA_AUTH_PASSWORD_JWT_SECRET }}
      - LBA_MAGICLINK_JWT_SECRET={{ vault.LBA_MAGICLINK_JWT_SECRET }}
      - LBA_CATALOGUE_URL=https://catalogue.intercariforef.org
      - LBA_AUTH_PASSWORD_HASH_ROUNDS={{ vault.LBA_AUTH_PASSWORD_HASH_ROUNDS }}
      - LBA_FTP_HOST={{ vault.LBA_FTP_HOST }}
      - LBA_FTP_CONSTRUCTYS_USER={{ vault.LBA_FTP_CONSTRUCTYS_USER }}
      - LBA_FTP_CONSTRUCTYS_PASSWORD={{ vault.LBA_FTP_CONSTRUCTYS_PASSWORD }}
      - LBA_FTP_OCAPIAT_USER={{ vault.LBA_FTP_OCAPIAT_USER }}
      - LBA_FTP_OCAPIAT_PASSWORD={{ vault.LBA_FTP_OCAPIAT_PASSWORD }}
      - LBA_AKTO_GRANT_TYPE={{ vault.LBA_AKTO_GRANT_TYPE }}
      - LBA_AKTO_CLIENT_ID={{ vault.LBA_AKTO_CLIENT_ID }}
      - LBA_AKTO_CLIENT_SECRET={{ vault.LBA_AKTO_CLIENT_SECRET }}
      - LBA_AKTO_SCOPE={{ vault.LBA_AKTO_SCOPE }}
      - LBA_ENTREPRISE_API_KEY={{ vault.LBA_ENTREPRISE_API_KEY }}
      - LBA_LBA_APPLICATION_NAME={{ vault.LBA_LBA_APPLICATION_NAME }}
      - LBA_LBA_ACCESS_KEY={{ vault.LBA_LBA_ACCESS_KEY }}
      - LBA_PE_CLIENT_ID={{ vault.LBA_PE_CLIENT_ID }}
      - LBA_PE_SECRET_ID={{ vault.LBA_PE_SECRET_ID }}

    volumes:
      - /opt/doctrina/data/server:/data

  ui:
    environment:
      - SENTRY_ORG=mna-idea
      - SENTRY_PROJECT=labonnealternance-ui
      - SENTRY_AUTH_TOKEN={{ vault.SENTRY_AUTH_TOKEN }}
      - SERVER_SENTRY_DSN={{ vault.SERVER_SENTRY_DSN }}
      - UI_SENTRY_DSN={{ vault.UI_SENTRY_DSN }}

  mongodb:
    volumes:
      - /opt/doctrina/data/mongodb/db:/data/db
      - /opt/doctrina/data/mongodb/configdb:/data/configdb
      - /opt/doctrina/data/mongodb/backups:/data/backups
      - /opt/doctrina/.overrides/mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  elasticsearch:
    volumes:
      - /opt/doctrina/data/elasticsearch:/usr/share/elasticsearch/data

  metabase:
    image: metabase/metabase:v0.44.6
    container_name: doctrina_metabase
    mem_limit: 3g
    volumes:
      - /opt/doctrina/data/metabase:/data/metabase
    depends_on:
      - mongodb
    environment:
      MB_DB_FILE: /data/metabase/metabase.db
      MB_SITE_LOCALE: fr
    restart: always
    networks:
      - doctrina_network
