- name: Stoppe tous les conteneurs applicatifs
  shell: "bash /opt/lba/stop-app.sh"

- name: "Clone du repository (branche : {{ git_revision }})"
  git:
    repo: "https://github.com/mission-apprentissage/doctrina.git"
    version: "{{ git_revision }}"
    force: yes
    accept_hostkey: yes
    dest: /opt/lba/repository

- name: Création des répertoires 'overrides'
  file:
    path: "/opt/lba/.overrides/{{ item.path }}/"
    state: directory
  with_filetree:
    - app/.overrides/common/
    - app/.overrides/{{ env_type }}/
  when: item.state == 'directory'

- name: Copie des fichiers 'overrides'
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/opt/lba/.overrides/{{ item.path }}"
  with_filetree:
    - app/.overrides/common/
    - app/.overrides/{{ env_type }}/
  when: item.state == 'file'

- name: Root only pour tous les répertoires applicatifs
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: 770
  with_items:
    - "/opt/lba/tools"
    - "/opt/lba/repository"
    - "/opt/lba/data"
    - "/opt/lba/backups"
    - "/opt/lba/.overrides"

- name: Ensure elasticsearch container can write in its directory
  file:
    path: /opt/lba/data/elasticsearch
    owner: 1000
    group: 1000
    state: directory

- name: Ensure clamav container can write in its directory
  file:
    path: /opt/lba/data/clamav
    owner: 100
    group: 101
    state: directory

- name: Add cron to rotate nginx files
  ansible.builtin.cron:
    name: "rotate_nginx_log_files"
    minute: "0"
    hour: "1"
    job: "bash /opt/lba/tools/rotate-nginx-log-files.sh >> /var/log/cron.log 2>&1"

- name: Add cron to reload app automatically
  when: env_type == "recette"
  ansible.builtin.cron:
    name: "reload-app"
    minute: "*/1"
    hour: 8-20
    weekday: 1-5
    job: "bash /opt/lba/reload-app.sh >> /var/log/cron.log 2>&1"
