habilitations:
  - username: kevin
    name: Kevin Barnoin
    gpg_key: 7F5A88DA2A9EEEF2
    authorized_keys:
      - "https://github.com/kevbarns.keys"
  - username: aleruyet
    name: Alan Le Ruyet
    gpg_key: 2AEF45D8C40959EE
    authorized_keys:
      - "https://github.com/alanlr.keys"

gpg_keys: "{{ habilitations  | map(attribute='gpg_key', default='') | select() | join(',')}}"
