version: "2.4"
services:
  server:
    environment:
      - DOCTRINA_ENV=production
      - DOCTRINA_LOG_LEVEL=info
      - DOCTRINA_LOG_DESTINATIONS=stdout,mongodb,slack
      - DOCTRINA_PUBLIC_URL=https://doctrina.apprentissage.beta.gouv.fr
      - DOCTRINA_MONGODB_URI=mongodb://doctrina:{{ vault.DOCTRINA_MONGODB_USER_PASSWORD }}@mongodb:27017/doctrina?authSource=admin&retryWrites=true&w=majority
      - DOCTRINA_API_KEY={{ vault.DOCTRINA_API_KEY }}
      - DOCTRINA_AUTH_PASSWORD_HASH_ROUNDS=10000
      - DOCTRINA_AUTH_USER_JWT_SECRET={{ vault.DOCTRINA_AUTH_USER_JWT_SECRET }}
      - DOCTRINA_AUTH_ACTIVATION_JWT_SECRET={{ vault.DOCTRINA_AUTH_ACTIVATION_JWT_SECRET }}
      - DOCTRINA_AUTH_PASSWORD_JWT_SECRET={{ vault.DOCTRINA_AUTH_PASSWORD_JWT_SECRET }}
      - DOCTRINA_SLACK_WEBHOOK_URL={{ vault.DOCTRINA_SLACK_WEBHOOK_URL }}
      - CATALOGUE_URL=https://catalogue.apprentissage.beta.gouv.fr

  ui:
    environment:
      - DOCTRINA_ENV=production
      - DOCTRINA_PUBLIC_URL=https://doctrina.apprentissage.beta.gouv.fr
    volumes:
      - /opt/doctrina/.overrides/ui/robots.txt:/app/public/robots.txt:ro

