version: "2.4"
services:
  reverse_proxy:
    volumes:
      - ./reverse_proxy/production/includes:/etc/nginx/templates/includes/env
      - ./reverse_proxy/production/conf.d:/etc/nginx/templates/conf.d/env

  server:
    environment:
      - LBA_ENV=production
      - LBA_LOG_LEVEL=info
      - LBA_LOG_DESTINATIONS=stdout,mongodb,slack
      - LBA_PUBLIC_URL=https://labonnealternance.apprentissage.beta.gouv.fr
      - LBA_PUBLIC_URL_ESPACE_PRO=https://labonnealternance.apprentissage.beta.gouv.fr/espace-pro
      - LBA_SMTP_AUTH_USER={{ vault.LBA_SMTP_AUTH_USER }}
      - LBA_SMTP_AUTH_PASS={{ vault.LBA_SMTP_AUTH_PASS }}
      - LBA_SMTP_PORT={{ vault.LBA_SMTP_PORT }}
      - LBA_SMTP_HOST={{ vault.LBA_SMTP_HOST }}
      - LBA_SENDINBLUE_WEBHOOK_API_KEY={{ vault[env_type].LBA_SENDINBLUE_WEBHOOK_API_KEY }}
      - LBA_SENDINBLUE_API_KEY={{ vault.LBA_SENDINBLUE_API_KEY }}
      - LBA_API_KEY={{ vault[env_type].LBA_API_KEY }}

  ui:
    environment:
      - LBA_ENV=production
      - LBA_PUBLIC_URL=https://labonnealternance.apprentissage.beta.gouv.fr
    volumes:
      - /opt/lba/.overrides/ui/robots.txt:/app/public/robots.txt:ro

  ui_espace_pro:
    build:
      args:
        - REACT_APP_BASE_URL=https://labonnealternance.apprentissage.beta.gouv.fr/api
        - REACT_APP_METABASE_URL=https://labonnealternance.apprentissage.beta.gouv.fr/metabase
        - REACT_APP_ENV=production

  metabase:
    environment:
      MB_SITE_URL: https://labonnealternance.apprentissage.beta.gouv.fr/metabase
